language: ruby
rvm:
  - 2.5
  - 2.6
bundler_args: --without production
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres