language: ruby
rvm:
  - 2.5
  - 2.6
bundler_args: --without production
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:create db:test:prepare
  - bundle exec rails webpacker:compile
cache:
  yarn: true
  directories:
    - node_modules
install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn install